server:
  port: 7001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuiyubing/cloud_demo.git
          search-paths: config_repository