server:
  port: 10086
spring:
  application:
    name: my-server
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10086/eureka