spring:
  application:
    name: ser3
server:
  port: 10088
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    eviction-interval-timer-in-ms: 2000
    enable-self-preservation: false
    service-url:
      defaultZone: http://localhost:10087/eureka,http://localhost:10086/eureka,http://localhost:10088/eureka
