zuul:
  prefix: /api # 添加路由前缀
  routes:
    user-server: # 这里是路由id，随意写
      path: /user-server/** # 这里是映射路径
      url: http://127.0.0.1:90 # 映射路径对应的实际url地址

ratelimit:
  key-prefix: user-server #请求的key的前缀
  enabled: true
  behind-proxy: true #代理之后
  default-policy: #针对所有的路由配置的策略
    limit: 10 #请求数量限制
    quota: 1000 #请求时间限制（毫秒）
    refresh-interval: 60 # 刷新时间窗口的时间（秒）
    type:  #可选 限流方式
    - user
    - origin
    - url